system:
  mode: 1 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: False
  amp_level: 'O2'
  seed: 42
  log_interval: 1
  val_while_train: True
  drop_overflow_update: False

model:
  type: det
  transform: null
  backbone:
    name: det_resnet50
    pretrained: True
  neck:
    name: DRRGFPN
#    in_channels: [ 256, 512, 1024, 2048 ]
#    out_channels: 32
    out_channels: 128
  head:
    name: DRRGHead
#    in_channels: 32
    text_region_thr: 0.3
    center_region_thr: 0.4

postprocess:
  name: DRRGPostprocess
  link_thr: 0.8

metric:
  name: DetMetric
  main_indicator: f-score

loss:
  name: DRRGLoss

scheduler:
  scheduler: polynomial_decay
  lr: 0.007
  num_epochs: 1200
  decay_rate: 0.9
  warmup_epochs: 3

optimizer:
  opt: SGD
  filter_bias_and_bn: false
  momentum: 0.9
  weight_decay: 1.0e-4

# only used for mixed precision training
loss_scaler:
  type: dynamic
  loss_scale: 512
  scale_factor: 2
  scale_window: 1000

train:
  ckpt_save_dir: './tmp_det_npu'
  dataset_sink_mode: True
  dataset:
    type: DetDataset
    dataset_root: /home/tongli/data/ctw1500/
    data_dir: train_images
    label_file: train_det_gt.txt
    sample_ratio: 0.01
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
      - ColorJitter:
          brightness: 0.12549019607843137
          saturation: 0.5
      - RandomScaling:
      - RandomCropFlip:
          crop_ratio: 0.5
      - RandomCropPolyInstances:
          crop_ratio: 0.8
          min_side_ratio: 0.3
      - RandomRotatePolyInstances:
          rotate_ratio: 0.5
          max_angle: 60
          pad_with_fixed_color: False
      - SquareResizePad:
          target_size: 800
          pad_ratio: 0.6
      - IaaAugment:
          Fliplr: { p: 0.5 }
      - RandomCropWithBBox:
          max_tries: 10
          min_crop_ratio: 0.1
          crop_size: [ 640, 640 ]
          p: 1.0
      - DRRGTargets:
      - NormalizeImage:
          bgr_to_rgb: False
          is_hwc: True
          mean: imagenet
          std: imagenet
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visualize
    output_columns: ['image', 'gt_text_mask', 'gt_center_region_mask', 'gt_mask',
            'gt_top_height_map', 'gt_bot_height_map', 'gt_sin_map',
            'gt_cos_map', 'gt_comp_attribs']
#    output_columns: ['image'] # for debug op performance
    net_input_column_index: [0, 8] # input indices for network forward func in output_columns
    label_column_index: [1, 2, 3, 4, 5, 6, 7, 8] # input indices marked as label

  loader:
    shuffle: True
    batch_size: 1
    drop_remainder: True
    num_workers: 1

eval:
  ckpt_load_path: tmp_det_npu/best.ckpt
  dataset_sink_mode: False
  dataset:
    type: DetDataset
    dataset_root: /home/tongli/data/ctw1500/
    data_dir: test_images
    label_file: test_det_gt.txt
    sample_ratio: 1.0
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
      - DetResize:
          target_size: [ 1024, 1024 ] # h, w
          keep_ratio: True
          padding: True
      - NormalizeImage:
          bgr_to_rgb: False
          is_hwc: True
          mean: imagenet
          std: imagenet
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the labels for evaluation
    output_columns: [ 'image', 'polys', 'ignore_tags', 'shape_list'  ]
    net_input_column_index: [0] # input indices for network forward func in output_columns
    label_column_index: [1, 2] # input indices marked as label

  loader:
    shuffle: False
    batch_size: 1 # TODO: due to dynamic shape of polygons (num of boxes varies), BS has to be 1
    drop_remainder: False
    num_workers: 2
